lab16/L16/L14/Models/VideoContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace L14.Models
{
    public class VideoContext:DbContext
    {
        public DbSet<VideoModel> VideoModels { get; set; }
    }
}

lab16/L16/L14/Models/VideoModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.IO;
using System.Linq;
using System.Web;

namespace L14.Models
{
    public class VideoModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string Title { get; set; }
        //public FileStream FileStream { get;  set; }

        public VideoModel() { }
        public  VideoModel(string title)
        {
            Title = title;
            
            //FileStream = new FileStream(@"E:\Work\ПИС\Проекты\16\L14\L14\Video\" + Id+Path.GetExtension(title), FileMode.Open, FileAccess.Read);
        }


    }
}

lab16/L16/L14/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace L14.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

lab16/L16/L14/Controllers/VideoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace L14.Controllers
{
    public class VideoController : Controller
    {
        Models.VideoContext videoContext = new Models.VideoContext();

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            return View(videoContext.VideoModels.AsEnumerable());


        }
        public ActionResult Index()
        {

            //return View();    
            ViewBag.fileId = videoContext.VideoModels.First().Id.ToString();

            return View(videoContext.VideoModels.AsEnumerable());

        }
        
        public ActionResult Video()
        {
            return PartialView(videoContext.VideoModels.AsEnumerable());
        }
        
        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file)
        {
            if (file != null && Path.GetExtension(file.FileName).Length>0)
            {
                Models.VideoModel a = new Models.VideoModel(file.FileName);
                videoContext.VideoModels.Add(a);
                videoContext.SaveChanges();
                var fileSavePath = HttpContext.Server.MapPath("~/VideoFiles\\") + a.Id  + Path.GetExtension(file.FileName);
                file.SaveAs(fileSavePath);
                ViewBag.fileId =a.Id.ToString() ;
            }
            
            return View("Index", videoContext.VideoModels.AsEnumerable());
        }
        
        public FileStreamResult GetVideo(string id)
        {
                return new FileStreamResult(new FileStream(HttpContext.Server.MapPath("~/VideoFiles\\") + id + ".mp4", FileMode.Open), "video/mp4");
        }
        public ActionResult SelectVideo(string id)
        {
            ViewBag.fileId = id;
            return View("Index",videoContext.VideoModels.AsEnumerable());

        }
        /*
        Models.VideoContext phoneContext = new Models.VideoContext();
        public ActionResult Browse()
        {
            return View("Browse", phoneContext.PhoneModels.AsEnumerable());
        }
        public ActionResult Add()
        {
            return View("Add");
        }
        [HttpPost]
        public ActionResult Add(Models.aaa phoneModel)
        {
            if (phoneModel.BDay < DateTime.Now.AddYears(-120))
            {
                ModelState.AddModelError("BDay", "Ошибка даты рождения");
            }
            if (ModelState.IsValid)
            {
                phoneContext.PhoneModels.Add(phoneModel);
                phoneContext.SaveChanges();
                return View("Browse", phoneContext.PhoneModels.AsEnumerable());
            }
            else return View();
        }
        public ActionResult Update(string id)
        {
            return View("Update", phoneContext.PhoneModels.Find(id));
        }
        [HttpPost]
        public ActionResult Update(Models.aaa phoneModel)
        {
            if (ModelState.IsValid)
            {
                phoneContext.Entry(phoneModel).State = System.Data.Entity.EntityState.Modified;
                phoneContext.SaveChanges();
                return View("Browse", phoneContext.PhoneModels.AsEnumerable());
            }
            return View("Update");
        }
        public ActionResult Delete(string id)
        {
            Models.aaa model = phoneContext.PhoneModels.Find(id);
            if (ModelState.IsValid && model != null)
            {
                phoneContext.PhoneModels.Remove(model);
                phoneContext.SaveChanges();
            }
            else
            {
                ViewBag.ErrorMessage = "Delete: Error";
            }
            return View("Browse", phoneContext.PhoneModels.AsEnumerable());
        }
        */
    }
}

lab16/L16/L14/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

lab16/L16/L14/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

lab16/L16/L14/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

lab16/L16/L14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    -->
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

lab16/L16/L14/Views/Video/AAA.cshtml
@model L14.Models.VideoModel

@{
    ViewBag.Title = "AAA";
}

<h2>AAA</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>VideoModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

lab16/L16/L14/Views/Video/Index.cshtml
@using L14.Models
@model IEnumerable<L14.Models.VideoModel>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2> 
<p>


    <h2>Upload</h2>
    @using (Html.BeginForm("Upload", "Video", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
           
            <div class="form-group">
                <div class="col-md-10">
                    <input type="file" name="file" accept="video/*"/>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Загрузить" class="btn btn-primary"  />
                </div>
            </div>
           
        </div>
    }

    <!--Html.ActionLink("Загрузить видео на сервер", "Upload")-->
</p>
@Html.Partial("Player", (string)ViewBag.fileId)
 @Html.Partial("Video",Model)

lab16/L16/L14/Views/Video/Player.cshtml
@model string
<h3>Partial view with  Player </h3>
<script>
    console.log("lalalalala");
</script>

<video width="1024"  controls autoplay="autoplay"  loop>
    <source src='@Url.Action("GetVideo","Video",new  { id= Model })' type="video/mp4"/>
</video>
 

lab16/L16/L14/Views/Video/Upload.cshtml
@model L14.Models.VideoModel

@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="file" value="Загрузить видео" class="btn btn-default" />
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

lab16/L16/L14/Views/Video/Video.cshtml
@model IEnumerable<L14.Models.VideoModel>
<h3>Partial view with all Videos on Server</h3>

<table class="table">
  

@foreach (var item in Model) {
    <tr>
        <td>
            <a href='@Url.Action("SelectVideo",new { id = item.Id })'>@item.Title</a>
            <!--Url.Action("SelectVideo", "Video",item)-->
           
        </td>
        
    </tr>
}

</table>
<!--Html.DisplayFor(modelItem => item.Title)-->